name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/rust-npm-publish-local.yml
    with:
      binaries: 'pm'
      platforms: 'macos-arm64'
      main_binary: pm
      npm_enabled: true
      npm_directory: npm
      tag_name: ${{ github.event.inputs.tag || github.ref_name }}
      rust_version: 'stable'
      node_version: '20'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
